# VISUAL CONFIGURATION
background_opacity 1

resize_in_steps yes
window_margin_width    1
remember_window_size no
initial_window_width 82c
initial_window_height 24c

# Turn off the damn bell
enable_audio_bell no 

# Turn on remote control
allow_remote_control yes

# DISABLE CONFIRMATION
confirm_os_window_close 2
# FONT FAMILY
font_family      VictorMono Nerd Font Mono
font_size 13.0
##################################
# ColorScheme
##################################
include everforest-dark-medium.conf

