;==========================================================
[everforest]
black      = #2d353b
dark       = #232a2e
disabled   = #475258
red        = #e67e80
red-alt    = #514045
orange     = #e69875
orange-mat = #e69875
yellow     = #dbbc7f
yellow-mat = #dbbc7f
green      = #a7c080
aqua       = #83c092
blue       = #7fbbb3
blue-alt   = #7fbbb3
grey       = #859289
dark-grey  = #232a2e
cream      = #d3c6aa
white      = #d3c6aa
transparent  = #00000000
Stransparent = #CC232A2E

[colors]
urgent = ${everforest.red}
success = ${everforest.aqua}
warning = ${everforest.yellow}
foreground = ${everforest.cream}
