;==========================================================
[module/rofi]
type=custom/text
format=""
format-padding=3
click-left= exec rofi -show drun -disable-history -show-icons
format-foreground=${everforest.black}
format-background=${everforest.yellow}

;==========================================================
[module/ss]
type=custom/text
format="  "
format-foreground=${everforest.black}
format-background=${everforest.transparent}

;==========================================================
[module/i3]
type = internal/i3
enable-scroll = false
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
fuzzy-match = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;󰭛
ws-icon-6 = 7;
ws-icon-7 = 8;󰚀

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${everforest.red-alt} 
label-mode-foreground = ${everforest.white}

label-focused = %icon%
label-focused-font = 5
label-focused-foreground = ${everforest.cream}
label-focused-underline = ${everforest.yellow}
label-focused-padding = 1

label-unfocused = %icon%
label-unfocused-font = 5
label-unfocused-foreground = ${everforest.blue}
label-unfocused-padding = 1

label-visible = %icon%
label-visible-underline = ${everforest.red}
label-visible-padding = 1

label-urgent = %icon%
label-urgent-font = 5
label-urgent-foreground = ${everforest.red}
label-urgent-underline = ${everforest.red-alt}
label-urgent-padding = 1

label-separator = " "
label-separator-padding = 1
label-separator-foreground = ${everforest.transparent}

;==========================================================
[module/powermenu]
type = custom/menu

expand-right = false
format = <menu><label-toggle>
format-spacing = 1

label-open = ""
label-open-foreground = ${colors.urgent}
format-underline= ${everforest.red}

label-close = "Cancel <"
label-close-foreground = ${colors.success}

label-separator = |
label-separator-foreground = ${colors.foreground}

; Main menu
menu-0-0 = "Power Off"
menu-0-0-exec = #powermenu.open.2
menu-0-0-foreground = ${colors.urgent}

menu-0-1 = "Reboot"
menu-0-1-exec = #powermenu.open.1
menu-0-1-foreground = ${colors.warning}

; Reboot confirmation
menu-1-0 = "Reboot"
menu-1-0-exec = systemctl reboot
menu-1-0-foreground = ${colors.urgent}

; Shutdown confirmation
menu-2-0 = "Power Off"
menu-2-0-exec = systemctl poweroff
menu-2-0-foreground = ${colors.urgent}

;==========================================================
[module/xwindow]
type = internal/xwindow
format-prefix="[   ]"
format-margin=2
format-prefix-foreground=${everforest.cream}

label = %title:0:100:%
label-foreground = ${everforest.cream}
label-padding-left=4
label-padding-right=4

;==========================================================
[module/time]
type = internal/date
interval = 1
format-prefix = "[   ]"
format-prefix-foreground=${everforest.aqua}
format-underline= ${everforest.aqua}

date = %a  %d %b  %H:%M:%S 
label =%date% 
label-foreground = ${everforest.cream}
label-padding-left=2
label-padding-right=2

;==========================================================
[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "[   ]"
format-volume-prefix-foreground = ${everforest.blue-alt}
format-volume = <label-volume>
format-volume-underline= ${everforest.blue-alt}

label-volume = %percentage%%
label-volume-foreground= ${everforest.cream}
label-volume-padding-left=2
label-volume-padding-right=2

label-muted = [  ]  muted
label-muted-foreground = ${everforest.red}
label-muted-underline = ${everforest.red}
label-muted-padding=2

;==========================================================
[module/wlan]
type = internal/network
interface = wlp15s0
interval = 3

format-connected = <ramp-signal> <label-connected>
format-connected-underline = ${everforest.green}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-0-foreground = ${everforest.red}
ramp-signal-1-foreground = ${everforest.orange}
ramp-signal-2-foreground = ${everforest.yellow}
ramp-signal-3-foreground = ${everforest.green}
ramp-signal-4-foreground = ${everforest.green}

label-connected = %essid%  %signal%%
label-connected-foreground = ${everforest.cream}
label-connected-padding-left = 2
label-connected-padding-right = 2

format-disconnected = <label-disconnected>
label-disconnected = [  ] no wifi
label-disconnected-foreground = ${everforest.red}
label-disconnected-padding = 2

;==========================================================
[module/tray]
type = internal/tray
tray-spacing = 2
tray-background = ${everforest.black}



